In [8]:
!python setup.py build_ext  --inplace

running build_ext


In [9]:
!ls

build				       game.cpp
build_cython_wrapper.ipynb	       game.cpython-38-x86_64-linux-gnu.so
evolve.cc			       game.pyx
evolve.cpython-38-x86_64-linux-gnu.so  setup.py
evolve.h


In [5]:
import numpy as np

In [1]:
from game import GameField

In [2]:
g = GameField(b=1.81, L=5)
g.L

5

In [3]:
g.field

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [6]:
L = 5
field = np.zeros((L, L))
field[:, 2] = 1

g = GameField(b=1.81, L=5)
g.field = field

In [7]:
g.field

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int32)

In [7]:
g.evolveQ(num_steps=1)
g.field

array([[0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0]], dtype=int32)